# Filter for samples

25 -> positives
75 -> negatives

Scored

In [135]:
import pandas as pd

df = pd.read_csv('/Users/natchalin_/Projects/final_project/Lloyds/API/flat_pot.csv')

In [136]:
df_pos = df[df['label'] == 1].sample(n = 25, random_state = 40)

In [137]:
df_neg = df[df['label'] == 0].sample(n = 75, random_state = 40)

In [138]:
df_sample = pd.concat([df_pos, df_neg], ignore_index = True)

In [139]:
df_sample['label'].value_counts()

label
0    75
1    25
Name: count, dtype: int64

In [140]:
df_sample = df_sample[['com_num', 'name', 'label']]

In [141]:
df_sample['relationship'] = 'prospect'

In [142]:
df_sample_final = df_sample.drop(columns = ['label'])

In [143]:
df_sample_final = df_sample_final.rename(columns = {'com_num': 'company_number', 'name': 'company_name'})

In [144]:
df_sample_final.to_csv('sample.csv')

# Combine the scores

In [145]:
scored = pd.read_csv('leads copy.csv')

In [146]:
scored = scored[['com_num', 'name', 'gated']]

In [147]:
merged = scored.merge(df_sample_final, left_on='com_num', right_on='company_number', how='left')

In [148]:
merged = merged[['com_num', 'name', 'gated','relationship']]

In [151]:
merged

     com_num                                  name     gated relationship
0   06494044  ELM VILLA & MADELEY PRACTICE LIMITED  0.983605     prospect
1   11723501    LIVERPOOL EDGE (COPPERAS HILL) LTD  0.962658     prospect
2   SC349083                      ECI 9 GP LIMITED  0.956579     prospect
3   SC495323                         H&H (EDI) LTD  0.935789     prospect
4   SC572380          BRIARHILL PROPERTIES LIMITED  0.918789     prospect
..       ...                                   ...       ...          ...
95  11949076             FIFTY-FIFTH FILMS LIMITED  0.126921     prospect
96  02103665                    MARCELLINO LIMITED  0.126000     prospect
97  06857120                          ANGELO K LTD  0.125395     prospect
98  09503392                  DCC TELECOMS LIMITED  0.111737     prospect
99  08398890                       ANANTH & JS LTD  0.100500     prospect

[100 rows x 4 columns]

In [150]:
df_sample

     com_num                                 name  label relationship
0   10941988    BOWHILL BUILDING SERVICES LIMITED      1     prospect
1   12591963     PURE COLLECTION CASHMERE LIMITED      1     prospect
2   SC683772  ALLAN & HAMILTON PROPERTIES LIMITED      1     prospect
3   09674295                      MAYA HEALTH LTD      1     prospect
4   11020713                         ALLPHARM LTD      1     prospect
..       ...                                  ...    ...          ...
95  07987818        AL REHMAN WELFARE PROJECT LTD      0     prospect
96  SC495323                        H&H (EDI) LTD      0     prospect
97  09064817                        AEVUS LIMITED      0     prospect
98  03972759         ALLBECK DEVELOPMENTS LIMITED      0     prospect
99  10699734                       ALNIRE LIMITED      0     prospect

[100 rows x 4 columns]

In [156]:
merged_final = merged.merge(df_sample[['com_num','label']], on = 'com_num', how = 'left')

In [158]:
merged_final.to_csv('final_sample.csv')